### ISSUE TITLE
Tile group arrays

### ISSUE THREAD

**Issue by sampsyo** [cucapra/hbir#23]
In the `config` section, it should be possible to declare—in addition to _individual_ groups—_arrays_ of tile groups. A single group looks like this:

```
arrange t as {
   group foo at (...);
}
```

An array of tile groups might do this:

```
arrange t as {
   group foo[i] at (...);
}
```

In this setting, the `at` range for the tile group array should probably be able to refer to `i`, i.e., the index in the tile group array.

We should also probably support multi-dimensional (at least 2D) arrays.

**Comment by epeguero** [comment]
No code-gen for this yet, but the syntax parses and pattern-matching works!
