### ISSUE TITLE
Location binders for code blocks

### ISSUE THREAD

**Issue by sampsyo** [cucapra/hbir#24]
This is a big one. Following #23, we want code blocks to be able to refer to locations within tile group arrays.

The idea is that a code block like this:

```
foo {
     ...code...
}
```

means "every tile within the group called `foo` should run this code." So if you have an array of tile groups, it's fine to index a particular one. For example, if `bar` is a 2D array of tile groups, you can say:

```
bar[4][2] {
    ...code...
}
```

to tell a particular tile group within the array what to do.

But the _real_ power comes when you leave the array indices symbolic, to bind "coordinate" variables you can use in the code. Like this:

```
bar[x][y] {
    ...code that uses x and y...
}
```

This is how we'll get "real" SPMD-like programming.

**Comment by sampsyo** [comment]
Eventually we'll want to extend this for _nested_ tile groups.

**Comment by epeguero** [comment]
Now that group pattern matching is working, some `code` section brainstorming on how I would want to write code in HBIR has led me to this design/train of thought:

```
code {
  extern vv_add(a: float*, b: float*, length: int): float*;

  f : A[n_a][m_a], B[n_b,m_b] -> C[n_c, m_c] =

    | t.top_half.row[1].col[y] <- A[1][0:y/m_a] {truncate}, B[1][0:y/m_b] {truncate} =
      (A[rows_a][cols_a], B[rows_b][cols_b]){
        for(i in 0:rows_a) {
          C[i] = vv_add(A[i], B[i], cols_a)
        }
      }
    | ...
  ...
}
```

- First, I'd like to pattern match on the group which will run the code. In this example, on `t.top_half.row[1].col[y]`
- Next, I want to be able to explicitly declare what data slices will be sent to this group. This is done by `... <- A[1][0:y/m_a] {truncate}, B[1][0:y/m_b] {truncate}`. 
  - Notice that I think about annotations here to potentially deal with group size/data size misalignments generically over arbitrary sizes. It begins to feel here as if much of the `data` section can be merged into the `code` section.
- To compute these data slices, I need to bind variables over the size of the input arrays (in this example: `n_a, m_a, ...` etc)
- Finally, it's nice to operate on arrays with zero-based indices, so we bind the max dimension sizes to the code block `rows_a, cols_a, ...`, and let the compiler deduce the obvious mapping.
  - In the future, there may be less obvious mappings, as in the case of non-contiguous slices, for example

As a final syntactic note: if we intend to have each HBIR program denote exactly 1 function, then we can replace `code` with `f : A[...], B[...] -> C[...]`.

Thoughts?

**Comment by sampsyo** [comment]
Cool; these are useful proposals! To break it down point by point:

> First, I'd like to pattern match on the group which will run the code. In this example, on `t.top_half.row[1].col[y]`

Totally makes sense to me; this is totally the way to do it.

> `f : A[n_a][m_a], B[n_b,m_b] -> C[n_c, m_c] =`
> [...]
> To compute these data slices, I need to bind variables over the size of the input arrays (in this example: `n_a, m_a, ...` etc)

I think I understand what you're getting at here with the "type signature" for the function—it's less about declaring the inputs and outputs and more about just binding variables to their sizes so you can manipulate the ranges of the underlying arrays.

From a somewhat aesthetic perspective, however, I think it's a little weird to "declare" a "function" with "arguments" when those arguments are really globals by design that should be accessible everywhere. Put differently, the declarations of `A` and `B` and `C` reside elsewhere (namely in the data section, because these declarations are big and complicated), so it looks a little counter-intuitive to "declare" them again here as arguments.

Of course, you could make the argument that these declarations amount to _restrictions_ on which globals a given function can touch, which makes the function easier to understand locally. But it's worth acknowledging that somewhat exotic semantics clear.

> Finally, it's nice to operate on arrays with zero-based indices, so we bind the max dimension sizes to the code block `rows_a, cols_a, ...`, and let the compiler deduce the obvious mapping.

I really like this idea of declaring "slices" to make iteration easier! The loops now get to look like "iterate over this entire logical array" instead of "iterate in this funky pattern over part of the array." I'd submit that a more natural way to do this would be to declare new names just for the slice, rather than reusing the same name as the underlying array, something like this:

```
let A_slice = A[1][0:y/m_a]
[...]
A_slice[0]  # The first element of the above range.
```

For the sake of incremental progress, I propose that we don't need to do all these features at once. It's possible to have a working system at each step and to make iterative refinements by taking these steps, for example:

1. Pattern-match on the group that runs the code. What you do with those bound variables is totally up to you; you can even just `printf` them if you want.
2. Add a mechanism for declaring these "slice" things that make iteration more convenient. But calculating these indices might still be sort of inconvenient.
3. Finally, we can make _that_ mechanism for slicing more convenient by letting you bind names for array sizes or whatever.

How does that sound?

**Comment by epeguero** [comment]
As we mentioned in our meeting:
```
let myA = A[i];

move myA into local; 

release myA;
```
